### ISSUE TITLE
search

### ISSUE THREAD

**Issue by ingwinlu** [ingwinlu/IIxD#10]

**Comment by pawe** [comment]
ich
- [x] suchformular
- [x] testdaten
- [x] kontaktaufnahme

**Comment by pawe** [comment]
Ich sitze gerade daran den eigentlichen Plan zur Suche umzusetzen und finde gerade heraus, dass der Plan nicht ganz durchdacht war. Zumindest so wie ich ihn verstanden habe.

Sowie ich den Plan verstanden habe: 
1. Auswahl Typ: eines aus Event, Größe, Farbe, Bezeichnung (siehe Bild https://github.com/ingwinlu/IIxD/blob/master/documentation/first%20meeting/0326_002.jpg)
2. Eingabe/Auswahl davon (z.b. Eingebe eines Textes, wenn Bezeichnung ausgewählt ist)
3. Neue Auswahl eines Typs wird möglich
4. Auswahl dieses
5. Eingabe/Auswahl im nebenstehendem Feld
   ... usw.

Das Problem ist jetzt, dass wir nur zwei Felder haben die eingegeben werden können: Beschreibung und Event. Ich finde das Prozedere machts für nur zwei Eingabemöglichkeiten zu kompliziert.

Deswegen meine Frage, kommen bei der Eingabe mehr Felder hinzu? 

Zum Datum, was ist der Hintergrund? Ist es das Datum an dem ein Eintrag bei uns im System erstellt wurde, wann verloren wurde oder der eines Events?

**Comment by ingwinlu** [comment]
Ja, die suche ist noch nicht so implementiert wie wir es eigentlich geplant hätten

**Comment by pawe** [comment]
Wie haben wir die Suche eigentlich geplant? Im Bild vom Plan stehen noch so Dinge wie Farbe und Größe, die auch nicht mehr zum Plan gehören. Zumindest gehe ich davon aus, weil man sie auch nirgends eingeben kann.

So wie ich es verstanden habe, sollte es in diese Richtung gehen: Vor dem Suchfeld kann sich der Benutzer aussuchen, nach welchem Kriterium er sucht/filtert. Hat er eines definiert, taucht ein weiteres auf. Wie etwa in diesem Bild. Das "Event" ist eine Auswahlmöglichkeit unter "Description". Oder siehe meine Beschreibung oben.

<img width="595" alt="bildschirmfoto 2015-12-18 um 14 01 05" src="https://cloud.githubusercontent.com/assets/1403208/11897434/0789e378-a590-11e5-81e9-731861e1b90c.png"> 

Das macht Sinn, wenn wir mehrere Kriterien haben. Wir haben aber nur "Description" und "Event". Jetzt war meine Frage, kommen noch Kriterien dazu? Dazugehörend auch die Frage zum Datum. Für was steht es?

**Comment by ingwinlu** [comment]
Ja so wars ursprünglich geplant. Mit mehr Kriterien, mit mehr Möglichkeiten diese einzugeben usw. Da aber niemand was dafür getan hat isses bei dem minimalen Set das jetzt verfügbar ist geblieben.

Was das Datum soll weiß ich nicht. Hab nicht ich gemacht.

**Comment by pawe** [comment]
Danke für die schnelle Antwort!

Wenn keine Kriterien mehr dazukommen, dann wäre es meiner Meinung nach besser die Eingabe nicht aufzublasen. Und eher die Eventauswahl zu verbessern. Ich baue Dropdown Suche ( https://silviomoreto.github.io/bootstrap-select/examples/#live-search) ein.
