### ISSUE TITLE
Concept drafts

### ISSUE THREAD

**Issue by pawe** [ingwinlu/IIxD#2]
Sorry, a bit late.

![0326_001](https://cloud.githubusercontent.com/assets/1403208/11623669/c811eaa2-9cce-11e5-9ac4-f324b1f4e2a0.jpg)
![0326_002](https://cloud.githubusercontent.com/assets/1403208/11623672/cba1b2ba-9cce-11e5-8c25-8bab26854062.jpg)
![0326_003](https://cloud.githubusercontent.com/assets/1403208/11623674/ce3c1de4-9cce-11e5-9228-a2956900efc5.jpg)
![0326_004](https://cloud.githubusercontent.com/assets/1403208/11623676/d28ac1de-9cce-11e5-9397-56e65398c8c1.jpg)
![0326_005](https://cloud.githubusercontent.com/assets/1403208/11623682/d4ce22f6-9cce-11e5-93ae-776ad24d46a6.jpg)

**Comment by ingwinlu** [comment]
Do you want to add them to the repository? Might be nice to have them all there along with other documentation.

**Comment by ingwinlu** [comment]
added to the repo via #4
